name: "Deploy to NuGet"

on:
  push:
    tags:
      - "v*"

env:
  nuget: "https://api.nuget.org/v3/index.json"

jobs:
  deploy:
    name: Deploy ${{ matrix.config.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Avalonia.BreadcrumbBar
            
    env:
      project_file: ${{ matrix.config.name }}/${{ matrix.config.name }}.csproj
      output: ${{ matrix.config.name }}/bin/nuget
      
    steps:
      - name: Checkout
        uses: uses: actions/checkout@v7
      
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "10.x.x"
      
      - name: Restore Project
        shell: bash
        run: dotnet restore ${{ env.project_file }}
      
      - name: Build Project
        shell: bash
        run: dotnet build ${{ env.project_file }} --no-restore -c Release
      
      - name: Pull Version from Tag
        id: version
        uses: battila7/get-version-action@v2
      
      - name: Package Project
        shell: bash
        run: |
          dotnet pack ${{ env.project_file }} --no-restore                   \
          -c Release -o ${{ env.output }}                                    \
          -p:Version="${{ steps.version.outputs.version-without-v }}"        \
          -p:PackageVersion="${{ steps.version.outputs.version-without-v }}" \
      
      - name: Push to Package Server
        shell: bash
        run: |-
          dotnet nuget push ${{ env.output }}/*.nupkg \
          -k ${{ secrets.NUGET_AUTH }}                \
          -s ${{ env.nuget }}                         \